### ISSUE TITLE
Throws error when used with connect

### ISSUE THREAD

**Issue by keithws** [kwhitley/apicache#152]
node v10.15.0
connect v3.6.6
apicache v1.2.3

Trying to follow the sample usage, but using connect instead of express, throws the following error:

```
8:19:17 PM web.1 |  .../node_modules/apicache/src/apicache.js:170
8:19:17 PM web.1 |            res.header('cache-control', 'max-age=' + (duration / 1000).toFixed(0));
8:19:17 PM web.1 |                ^
8:19:17 PM web.1 |  TypeError: res.header is not a function
8:19:17 PM web.1 |      at ServerResponse.res.writeHead (.../node_modules/apicache/src/apicache.js:170:15)
8:19:17 PM web.1 |      at ServerResponse._implicitHeader (_http_server.js:199:8)
8:19:17 PM web.1 |      at write_ (_http_outgoing.js:597:9)
8:19:17 PM web.1 |      at ServerResponse.write (_http_outgoing.js:579:10)
8:19:17 PM web.1 |      at ServerResponse.res.write (.../node_modules/apicache/src/apicache.js:183:34)
8:19:17 PM web.1 |      at IncomingMessage.ondata (_stream_readable.js:693:20)
8:19:17 PM web.1 |      at IncomingMessage.emit (events.js:188:13)
8:19:17 PM web.1 |      at addChunk (_stream_readable.js:288:12)
8:19:17 PM web.1 |      at readableAddChunk (_stream_readable.js:269:11)
8:19:17 PM web.1 |      at IncomingMessage.Readable.push (_stream_readable.js:224:10)
[DONE] Killing all processes with signal  SIGINT
8:19:17 PM web.1 Exited with exit code null
```

**Comment by keithws** [comment]
I "fixed" it by replacing the `header()` calls with `setHeader()` calls. I'll have to see if that still works with express and check for any other express only calls.

**Comment by keithws** [comment]
Since both the Connect and the Express response objects inherit from the ServerResponse object in the node HTTP module, my fix works with both Express and Connect (possibly others too) so I submitted a pull request.

**Comment by kwhitley** [comment]
Sorted in `1.2.5+`

Thanks guys!

**Comment by keithws** [comment]
👍
