### ISSUE TITLE
uncaughtException The header content contains invalid characters

### ISSUE THREAD

**Issue by tomalex0** [kwhitley/apicache#34]
We are trying out Api cache  and its working  perfectly with redis client. But once we plugged in the SSO node module, read operation fails abruptly, i can see `[api-cache]: returning redis cached version of "/api/userdetails"` but something going wrong after that.

If i remove the SSO implementation everything works fine.

This is the first time i'm trying out api cache with the app which works fine with SSO module.

Please share your thoughts regarding what might be going wrong

```
[api-cache]: returning redis cached version of "/api/userdetails"
Thu, 11 Aug 2016 16:26:17 GMT uncaughtException The header content contains invalid characters
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ServerResponse.header (C:\Projects\hub\wayne\hub-webapp\node_modules\express\lib\response.js:719:10)
    at ServerResponse.header (C:\Projects\hub\wayne\hub-webapp\node_modules\express\lib\response.js:722:12)
    at C:\Projects\hub\wayne\hub-webapp\node_modules\apicache\lib\apicache.js:170:21
    at tryCatcher (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\promise.js:558:21)
    at Promise._settlePromise0 (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Projects\hub\wayne\hub-webapp\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

```

**Comment by tomalex0** [comment]
im using `nodejs  6.2.0 in windows 7`

![image](https://cloud.githubusercontent.com/assets/208168/17600278/a1b6e9be-5fb7-11e6-9ab4-496827823f14.png)

**Comment by tomalex0** [comment]
Atlast figured out the what was causing the issue, 

in our sso module we had below code , which kind of causing a change in  headers or so
`var shellExec = require('shelljs').exec;`
