### ISSUE TITLE
Null error in sendCachedResponse

### ISSUE THREAD

**Issue by matttilton** [kwhitley/apicache#57]
Im not exactly sure what is causing the issue but on occasion I get the following error.

TypeError: Cannot convert undefined or null to object 
    at Function.assign (<anonymous>)
    at sendCachedResponse (C:\Users\Matthew\Desktop\CDMMS\node_modules\apicache\src\apicache.js:129:12)
    at cache (C:\Users\Matthew\Desktop\CDMMS\node_modules\apicache\src\apicache.js:281:18)
    at Layer.handle [as handle_request] (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\Matthew\Desktop\CDMMS\node_modules\express\lib\router\index.js:280:7

Editing sendCachedResponse to include a check for null seems to resolve the issue 

function sendCachedResponse(response, cacheObject) {
   if (response._headers != null) {
     Object.assign(response._headers, cacheObject.headers, {
       'apicache-store': globalOptions.redisClient ? 'redis' : 'memory',
       'apicache-version': pkg.version
     })
   }

**Comment by kwhitley** [comment]
Thanks @matttilton!  Mind checking if `0.7.4` fixes it?

**Comment by matttilton** [comment]
The issue seems to be resolved. Thanks for the quick response.
