### ISSUE TITLE
Issue with callstack on Restify 5.0 & CORS

### ISSUE THREAD

**Issue by kokarn** [kwhitley/apicache#92]
I'm trying a fairly basic setup but can't get it to work. 
For some reason it exceeds the callstack.

It seems to me that the HEAD request for CORS preflight is making apicache trip, might that be it?

Node: 8.1.3
Restify: 5.0
apicache: 0.8.7
```javascript
const restify = require( 'restify' );
const apicache = require( 'apicache' );
const corsMiddleware = require( 'restify-cors-middleware' );

const server = restify.createServer( {
    name: 'REST API',
} );

const cache = apicache.middleware;
const cors = corsMiddleware( {
    allowHeaders: [ 'authorization' ],
    exposeHeaders: [ 'authorization' ],
    origins: [ '*' ],
} );

server.pre( cors.preflight );
server.use( cors.actual );
server.use( restify.plugins.bodyParser() );
server.use( restify.plugins.queryParser() );
server.use( restify.plugins.gzipResponse() );

server.get(
    '/:game/posts',
    cache( '1 minute' ),
    ( request, response ) => {
        // some db stuff
    }
);
```
```log
RangeError: Maximum call stack size exceeded
at ServerResponse.get (_http_outgoing.js:129:16)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
at ServerResponse.get (_http_outgoing.js:130:17)
at ServerResponse.getHeaders (/vagrant/rest-api/node_modules/restify/lib/response.js:120:17)
```

**Comment by kokarn** [comment]
This is probably related to https://github.com/restify/node-restify/issues/1374 even tho it's closed.

**Comment by kokarn** [comment]
Bug in restify

https://github.com/restify/node-restify/issues/1407
